const GITHUB_API = "https://api.github.com";

export class GitHubClient {
  constructor(private token: string) {}

  async getPullRequest(
    repoFullName: string,
    prNumber: number
  ): Promise<{ head: { ref: string; sha: string } }> {
    const res = await this.request(`/repos/${repoFullName}/pulls/${prNumber}`);
    return res as { head: { ref: string; sha: string } };
  }

  async postComment(
    repoFullName: string,
    issueNumber: number,
    body: string
  ): Promise<void> {
    await this.request(`/repos/${repoFullName}/issues/${issueNumber}/comments`, {
      method: "POST",
      body: JSON.stringify({ body }),
    });
  }

  async createBranch(
    repoFullName: string,
    branchName: string,
    sha: string
  ): Promise<void> {
    await this.request(`/repos/${repoFullName}/git/refs`, {
      method: "POST",
      body: JSON.stringify({ ref: `refs/heads/${branchName}`, sha }),
    });
  }

  async createPullRequest(
    repoFullName: string,
    title: string,
    body: string,
    head: string,
    base: string
  ): Promise<{ html_url: string; number: number }> {
    const res = await this.request(`/repos/${repoFullName}/pulls`, {
      method: "POST",
      body: JSON.stringify({ title, body, head, base }),
    });
    return res as { html_url: string; number: number };
  }

  async pushChanges(
    repoDir: string,
    repoCloneUrl: string,
    branchName: string
  ): Promise<void> {
    const { execFile } = await import("node:child_process");
    const { promisify } = await import("node:util");
    const execFileAsync = promisify(execFile);

    const authedUrl = repoCloneUrl.replace(
      "https://",
      `https://x-access-token:${this.token}@`
    );

    const gitOpts = { cwd: repoDir, timeout: 120_000 };

    await execFileAsync("git", ["checkout", "-b", branchName], gitOpts);
    await execFileAsync("git", ["add", "-A"], gitOpts);
    await execFileAsync(
      "git",
      ["commit", "-m", "chore: add observability instrumentation\n\nGenerated by otelagent"],
      gitOpts
    );
    await execFileAsync("git", ["push", authedUrl, branchName], gitOpts);
  }

  private async request(path: string, init?: RequestInit): Promise<unknown> {
    const res = await fetch(`${GITHUB_API}${path}`, {
      ...init,
      headers: {
        Authorization: `Bearer ${this.token}`,
        Accept: "application/vnd.github+json",
        "Content-Type": "application/json",
        "X-GitHub-Api-Version": "2022-11-28",
        ...init?.headers,
      },
    });

    if (!res.ok) {
      const text = await res.text();
      throw new Error(`GitHub API ${res.status}: ${text}`);
    }

    return res.json();
  }
}
