import { rm } from "node:fs/promises";
import { execFile } from "node:child_process";
import { mkdtemp } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { promisify } from "node:util";
import { runAgent, type AgentMode } from "../agent/index.js";
import { GitHubClient } from "./github.js";
import type { WebhookCommand } from "./webhook-parser.js";

const execFileAsync = promisify(execFile);

export async function handleAnalyzeCommand(
  command: WebhookCommand,
  github: GitHubClient,
  options: { model?: string; maxTurns?: number; maxBudgetUsd?: number; maxToolCalls?: number }
): Promise<void> {
  let tempDir: string | undefined;

  try {
    // React to the comment so the user knows we're working
    await github.postComment(
      command.repoFullName,
      command.prNumber,
      `🔍 Running observability analysis in **${command.mode.toUpperCase()}** mode on \`${command.headRef}\`…`
    );

    // Clone the PR head
    tempDir = await mkdtemp(join(tmpdir(), "otelagent-"));
    const authedUrl = command.repoCloneUrl.replace(
      "https://",
      `https://x-access-token:${github["token"]}@`
    );
    await execFileAsync(
      "git",
      ["clone", "--depth", "1", "--branch", command.headRef, authedUrl, tempDir],
      { timeout: 120_000 }
    );

    // Run the agent
    const result = await runAgent({
      repoDir: tempDir,
      mode: command.mode,
      model: options.model,
      maxTurns: options.maxTurns,
      maxBudgetUsd: options.maxBudgetUsd,
      maxToolCalls: options.maxToolCalls,
    });

    // Deliver results
    if (command.mode === "fix") {
      await deliverFix(command, github, tempDir, result.output);
    } else {
      await deliverComment(command, github, result.output, result);
    }
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    await github
      .postComment(
        command.repoFullName,
        command.prNumber,
        `❌ OtelAgent failed: ${msg}`
      )
      .catch(() => {}); // best-effort error reporting
    throw err;
  } finally {
    if (tempDir) {
      await rm(tempDir, { recursive: true, force: true }).catch(() => {});
    }
  }
}

async function deliverComment(
  command: WebhookCommand,
  github: GitHubClient,
  output: string,
  stats: { costUsd: number; numTurns: number; durationMs: number }
): Promise<void> {
  const footer = `\n\n---\n*OtelAgent — ${stats.numTurns} turns | $${stats.costUsd.toFixed(4)} | ${(stats.durationMs / 1000).toFixed(1)}s*`;
  await github.postComment(
    command.repoFullName,
    command.prNumber,
    output + footer
  );
}

async function deliverFix(
  command: WebhookCommand,
  github: GitHubClient,
  repoDir: string,
  summary: string
): Promise<void> {
  const branchName = `otelagent/fix/${command.headRef}`;

  await github.pushChanges(repoDir, command.repoCloneUrl, branchName);

  const pr = await github.createPullRequest(
    command.repoFullName,
    `chore: add observability instrumentation`,
    `## Observability Instrumentation\n\nGenerated by OtelAgent from PR #${command.prNumber}.\n\n${summary}`,
    branchName,
    command.headRef
  );

  await github.postComment(
    command.repoFullName,
    command.prNumber,
    `✅ OtelAgent created a fix PR: ${pr.html_url}`
  );
}
